[phases.install]
cmds = [
  'npm install --prefix apps/pos/backend',
  'npm install --prefix apps/pos/frontend'
]

[phases.build]
cmds = [
  'npm run build --prefix apps/pos/backend',
  'npm run build --prefix apps/pos/frontend'
]

[start]
cmd = 'node apps/pos/backend/dist/app.js'
