// The 22 tables that live inside every tenant's own schema — everything
// except users/roles, which stay in `public` (see tenantContext.ts /
// database.ts for how a tenant's search_path makes these resolve
// automatically for every existing unqualified query in the app).
//
// This is schema.sql's table set minus `roles`/`users`, with every
// `REFERENCES users(id)` qualified to `REFERENCES public.users(id)` since a
// fresh tenant schema has no local `users` table of its own. Statements run
// in dependency order, one at a time, against a session whose search_path
// is already set to the new tenant's schema (see tenant.service.ts).
export const TENANT_SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    color VARCHAR(20) DEFAULT '#6366f1',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS brands (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS tax_rates (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rate DECIMAL(5,2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    barcode VARCHAR(100),
    sku VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    selling_price DECIMAL(12,2) NOT NULL,
    cost_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    avg_cost DECIMAL(12,4) NOT NULL DEFAULT 0,
    category_id INTEGER REFERENCES categories(id),
    brand_id INTEGER REFERENCES brands(id),
    unit_type VARCHAR(50) DEFAULT 'piece',
    current_stock DECIMAL(12,3) DEFAULT 0,
    low_stock_level DECIMAL(12,3) DEFAULT 5,
    tax_rate DECIMAL(5,2) DEFAULT 0,
    image_url VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    allow_negative_stock BOOLEAN DEFAULT TRUE,
    costing_method VARCHAR(20),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode) WHERE barcode IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku)`,
  `CREATE INDEX IF NOT EXISTS idx_products_name ON products USING gin(to_tsvector('english', name))`,
  `CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id)`,
  `CREATE TABLE IF NOT EXISTS suppliers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS grn (
    id SERIAL PRIMARY KEY,
    grn_number VARCHAR(100) UNIQUE NOT NULL,
    supplier_id INTEGER REFERENCES suppliers(id),
    invoice_number VARCHAR(100),
    received_date DATE NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) DEFAULT 'completed',
    notes TEXT,
    created_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS grn_items (
    id SERIAL PRIMARY KEY,
    grn_id INTEGER NOT NULL REFERENCES grn(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity DECIMAL(12,3) NOT NULL,
    buying_price DECIMAL(12,4) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS product_batches (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    grn_item_id INTEGER REFERENCES grn_items(id),
    batch_number VARCHAR(100) NOT NULL,
    quantity_received DECIMAL(12,3) NOT NULL,
    quantity_remaining DECIMAL(12,3) NOT NULL,
    unit_cost DECIMAL(12,4) NOT NULL,
    expiry_date DATE,
    received_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_grn_supplier ON grn(supplier_id)`,
  `CREATE INDEX IF NOT EXISTS idx_grn_date ON grn(received_date)`,
  `CREATE INDEX IF NOT EXISTS idx_grn_items_product ON grn_items(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_product_batches_product ON product_batches(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_product_batches_grn_item ON product_batches(grn_item_id)`,
  `CREATE TABLE IF NOT EXISTS grn_returns (
    id SERIAL PRIMARY KEY,
    return_number VARCHAR(100) UNIQUE NOT NULL,
    grn_id INTEGER NOT NULL REFERENCES grn(id),
    notes TEXT,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS grn_return_items (
    id SERIAL PRIMARY KEY,
    grn_return_id INTEGER NOT NULL REFERENCES grn_returns(id) ON DELETE CASCADE,
    grn_item_id INTEGER NOT NULL REFERENCES grn_items(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity DECIMAL(12,3) NOT NULL,
    buying_price DECIMAL(12,4) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_grn_returns_grn ON grn_returns(grn_id)`,
  `CREATE TABLE IF NOT EXISTS stock_movements (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    movement_type VARCHAR(50) NOT NULL,
    quantity DECIMAL(12,3) NOT NULL,
    balance_before DECIMAL(12,3) NOT NULL,
    balance_after DECIMAL(12,3) NOT NULL,
    unit_cost DECIMAL(12,4),
    reference_type VARCHAR(50),
    reference_id INTEGER,
    notes TEXT,
    created_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON stock_movements(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_type ON stock_movements(movement_type)`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_date ON stock_movements(created_at)`,
  `CREATE TABLE IF NOT EXISTS shifts (
    id SERIAL PRIMARY KEY,
    shift_number VARCHAR(50) UNIQUE NOT NULL,
    opened_by INTEGER NOT NULL REFERENCES public.users(id),
    closed_by INTEGER REFERENCES public.users(id),
    open_time TIMESTAMP NOT NULL DEFAULT NOW(),
    close_time TIMESTAMP,
    opening_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
    expected_cash DECIMAL(12,2),
    actual_cash DECIMAL(12,2),
    cash_difference DECIMAL(12,2),
    total_sales DECIMAL(12,2) DEFAULT 0,
    total_cash_sales DECIMAL(12,2) DEFAULT 0,
    total_card_sales DECIMAL(12,2) DEFAULT 0,
    total_transactions INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'open',
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_shifts_status ON shifts(status)`,
  `CREATE INDEX IF NOT EXISTS idx_shifts_opened_by ON shifts(opened_by)`,
  `CREATE TABLE IF NOT EXISTS promotions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    discount_value DECIMAL(10,4),
    min_purchase_amount DECIMAL(12,2),
    min_purchase_qty INTEGER,
    buy_quantity INTEGER,
    get_quantity INTEGER,
    get_product_id INTEGER REFERENCES products(id),
    applies_to VARCHAR(50) DEFAULT 'all',
    category_id INTEGER REFERENCES categories(id),
    product_id INTEGER REFERENCES products(id),
    start_date DATE,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    priority INTEGER DEFAULT 0,
    created_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(is_active, start_date, end_date)`,
  `CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    credit_limit DECIMAL(12,2),
    current_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone) WHERE phone IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_customers_balance ON customers(current_balance)`,
  `CREATE TABLE IF NOT EXISTS customer_payments (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL DEFAULT 'cash',
    notes TEXT,
    received_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_customer_payments_customer ON customer_payments(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON customer_payments(created_at)`,
  `CREATE TABLE IF NOT EXISTS sales (
    id SERIAL PRIMARY KEY,
    sale_number VARCHAR(100) UNIQUE NOT NULL,
    shift_id INTEGER NOT NULL REFERENCES shifts(id),
    cashier_id INTEGER NOT NULL REFERENCES public.users(id),
    subtotal DECIMAL(12,2) NOT NULL,
    item_discount DECIMAL(12,2) DEFAULT 0,
    bill_discount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    total_amount DECIMAL(12,2) NOT NULL,
    cost_total DECIMAL(12,2) DEFAULT 0,
    profit DECIMAL(12,2) DEFAULT 0,
    payment_method VARCHAR(20) NOT NULL DEFAULT 'cash',
    cash_tendered DECIMAL(12,2) DEFAULT 0,
    card_amount DECIMAL(12,2) DEFAULT 0,
    change_amount DECIMAL(12,2) DEFAULT 0,
    status VARCHAR(20) DEFAULT 'completed',
    void_reason TEXT,
    notes TEXT,
    customer_name VARCHAR(255),
    customer_id INTEGER REFERENCES customers(id),
    is_vat_invoice BOOLEAN NOT NULL DEFAULT FALSE,
    vat_invoice_number VARCHAR(50),
    buyer_vat_reg_no VARCHAR(100),
    buyer_address TEXT,
    buyer_phone VARCHAR(50),
    delivery_date DATE,
    place_of_supply VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS sale_items (
    id SERIAL PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id),
    product_name VARCHAR(255) NOT NULL,
    barcode VARCHAR(100),
    quantity DECIMAL(12,3) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    original_price DECIMAL(12,2) NOT NULL,
    cost_price DECIMAL(12,4) NOT NULL DEFAULT 0,
    item_discount DECIMAL(12,2) DEFAULT 0,
    tax_rate DECIMAL(5,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) NOT NULL,
    promotion_id INTEGER REFERENCES promotions(id),
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS sale_item_taxes (
    id SERIAL PRIMARY KEY,
    sale_item_id INTEGER NOT NULL REFERENCES sale_items(id) ON DELETE CASCADE,
    tax_rate_id INTEGER REFERENCES tax_rates(id),
    tax_name VARCHAR(100) NOT NULL,
    tax_rate DECIMAL(5,2) NOT NULL,
    tax_amount DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sale_item_taxes_item ON sale_item_taxes(sale_item_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_shift ON sales(shift_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_cashier ON sales(cashier_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status)`,
  `CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id) WHERE customer_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items(product_id)`,
  `CREATE TABLE IF NOT EXISTS sale_returns (
    id SERIAL PRIMARY KEY,
    return_number VARCHAR(100) UNIQUE NOT NULL,
    sale_id INTEGER NOT NULL REFERENCES sales(id),
    shift_id INTEGER NOT NULL REFERENCES shifts(id),
    processed_by INTEGER NOT NULL REFERENCES public.users(id),
    return_reason TEXT,
    refund_method VARCHAR(20) NOT NULL DEFAULT 'cash',
    total_refund_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS sale_return_items (
    id SERIAL PRIMARY KEY,
    return_id INTEGER NOT NULL REFERENCES sale_returns(id) ON DELETE CASCADE,
    sale_item_id INTEGER NOT NULL REFERENCES sale_items(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    product_name VARCHAR(255) NOT NULL,
    quantity DECIMAL(12,3) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    cost_price DECIMAL(12,4) NOT NULL,
    refund_subtotal DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sale_returns_sale ON sale_returns(sale_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sale_returns_shift ON sale_returns(shift_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sale_return_items_ret ON sale_return_items(return_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sale_return_items_si ON sale_return_items(sale_item_id)`,
  `CREATE TABLE IF NOT EXISTS inventory_adjustments (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    adjustment_type VARCHAR(30) NOT NULL,
    quantity DECIMAL(12,3) NOT NULL,
    quantity_before DECIMAL(12,3) NOT NULL,
    quantity_after DECIMAL(12,3) NOT NULL,
    reason VARCHAR(255),
    notes TEXT,
    created_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMP DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    business_name VARCHAR(255) NOT NULL DEFAULT 'My Business',
    business_type VARCHAR(100) DEFAULT '',
    logo_data_url TEXT,
    address TEXT,
    phone VARCHAR(50),
    email VARCHAR(255),
    currency_code VARCHAR(10) NOT NULL DEFAULT 'USD',
    currency_symbol VARCHAR(10) NOT NULL DEFAULT '$',
    vat_registration_number VARCHAR(100),
    plan_key VARCHAR(20) NOT NULL DEFAULT 'basic',
    -- Explicit FeatureKey[] override, set by a marketing agent customizing a
    -- customer's package beyond its plan defaults (see requireFeature /
    -- planIncludes in data/plans.ts). NULL = use the plan's default features.
    custom_features JSONB,
    setup_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT settings_singleton CHECK (id = 1)
  )`,
  `CREATE TABLE IF NOT EXISTS vat_invoice_counter (
    id INTEGER PRIMARY KEY DEFAULT 1,
    next_number INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT vat_invoice_counter_singleton CHECK (id = 1)
  )`,
  `INSERT INTO vat_invoice_counter (id, next_number) VALUES (1, 1) ON CONFLICT (id) DO NOTHING`,
];
